name: paurakhi
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-312.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  #localization adding to the application
  intl: ^0.18.0

  adaptive_sizer: ^0.0.4
  #using the google fonts
  google_fonts: ^4.0.1
  
  #using the pinput for OTP
  pinput: ^2.2.31

  #used for routing 
  get: ^4.6.5

  #env 
  flutter_dotenv: ^5.0.2

  #image picker in flutter  and image cropper 
  image_picker: ^0.8.7+4
  image_cropper: ^3.0.3

  #state management
  provider: ^6.0.5
  flutter_bloc: ^8.1.2
  shared_preferences: ^2.1.0

  http: ^0.13.6

  webview_flutter: ^4.2.0

  #state management 

  #getting location pacgake
  geolocator: ^8.2.0
  geocoding: ^2.0.4

  connectivity: ^3.0.6

  flutter_html: ^3.0.0-beta.1

  flutter_launcher_icons: ^0.13.1

  
  eventsource: ^0.4.0

  #UI packages
  cached_network_image: ^3.2.3
  dropdown_button2: ^2.1.2
  sliding_switch: ^1.1.0
  restart_app: ^1.2.1
  awesome_dialog: ^3.1.0
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^14.1.1
  carousel_slider: ^4.2.1

flutter_icons:
  android: true
  ios: true 
  image_path: "assets/images/paurakhi1.png"
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0  
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/  
    - .env
    - .env.production
    - .env.development
